BookReviews.MVCWebApplication/Models/ErrorViewModel.cs
namespace BookReviews.MVCWebApplication.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BookReviews.MVCWebApplication/Controllers/AuthorController.cs
using ApplicationInterfaces;
using BookReviews.Models.Dto;
using Microsoft.AspNetCore.Mvc;

namespace BookReviews.MVCWebApplication.Controllers
{
    public class AuthorController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IAuthorApplicationService _authorApplicationService;

        public AuthorController(ILogger<HomeController> logger, IAuthorApplicationService authorApplicationService)
        {
            _logger = logger;
            _authorApplicationService = authorApplicationService;
        }

        public async Task<IActionResult> Index()
        {
            var authors = await _authorApplicationService.GetAllActiveAuthors();
            if(authors == null)
            {
                ViewBag.ErrorMessage = "Cannot find any authors.  Please check that the API is up and running.";
                return View();
            }
            return View(authors.OrderBy(z => z.LastName).ToList());
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var author = await _authorApplicationService.GetAuthorByIdAsync(id);
            return View(author);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(AuthorDto authorDto)
        {
            var author = await _authorApplicationService.SaveAuthorAsync(authorDto);
            if(author == null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Index");
            }
        }
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Add(AddAuthorDto addAuthorDto)
        {
            var author = await _authorApplicationService.AddAuthorAsync(addAuthorDto);
            if (author == null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var author = await _authorApplicationService.GetAuthorByIdAsync(id);
            var currentUserId = HttpContext.Session.GetInt32("UserID");
            if (currentUserId == null || author == null)
            {
                return RedirectToAction("Login", "Home");
            }
            var returnMe = await _authorApplicationService.DeleteAuthorAsync(author, id);
            return RedirectToAction("Index");
        }
    }
}

BookReviews.MVCWebApplication/Controllers/BookController.cs
using ApplicationInterfaces;
using ApplicationServices;
using BookReviews.Models.Dto;
using Microsoft.AspNetCore.Mvc;

namespace BookReviews.MVCWebApplication.Controllers
{
    public class BookController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IBookApplicationService _bookApplicationService;

        public BookController(ILogger<HomeController> logger, IBookApplicationService bookApplicationService)
        {
            _logger = logger;
            _bookApplicationService = bookApplicationService;
        }
        public async Task<IActionResult> Index()
        {
            var books = await _bookApplicationService.GetAllActiveBooks();
            if (books == null)
            {
                ViewBag.ErrorMessage = "Cannot find any books.  Please check that the API is up and running.";
                return View();
            }
            return View(books.OrderBy(z => z.Title).ToList());
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var book = await _bookApplicationService.GetBookByIdAsync(id);
            if (book == null)
            {
                ViewBag.ErrorMessage = "Cannot find book.";
                return View();
            }
            return View(book);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(BookDto bookDto)
        {
            var book = await _bookApplicationService.SaveBookAsync(bookDto);
            if (book == null)
            {
                ViewBag.ErrorMessage = "Cannot find book.";
                return View();
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Add(AddBookDto addBookDto)
        {
            var book = await _bookApplicationService.AddBookAsync(addBookDto);
            if (book == null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Index");
            }
        }
    }
}

BookReviews.MVCWebApplication/Controllers/HomeController.cs
using ApplicationInterfaces;
using BookReviews.Models.Dto;
using BookReviews.MVCWebApplication.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Http;

namespace BookReviews.MVCWebApplication.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IUserApplicationService _userApplicationService;

        public HomeController(ILogger<HomeController> logger, IUserApplicationService userApplicationService)
        {
            _logger = logger;
            _userApplicationService = userApplicationService;
        }

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> LoginAsync(UserDto objUser)
        {
            if (ModelState.IsValid)
            {
                if (objUser.Email == null || objUser.Password == null)
                {
                    return View();
                }

                var authenticated = await _userApplicationService.AuthenticateUserAsync(objUser.Email, objUser.Password);

                if (authenticated != null)
                {
                    HttpContext.Session.SetInt32("UserID", authenticated.Id);
                }

                return RedirectToAction("Index");
            }
            return View(objUser);
        }

        public IActionResult Index()
        {
            var userId = HttpContext.Session.GetInt32("UserID");
            if (userId == null)
            {
                return RedirectToAction("Login", "Home");
            }
            else
            {
                HttpContext.Session.SetInt32("UserID", (int)userId);
                return View();
            }
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

    }
}

BookReviews.MVCWebApplication/Controllers/ReviewController.cs
using ApplicationInterfaces;
using Microsoft.AspNetCore.Mvc;

namespace BookReviews.MVCWebApplication.Controllers
{
    public class ReviewController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IReviewApplicationService _reviewApplicationService;

        public ReviewController(ILogger<HomeController> logger, IReviewApplicationService reviewApplicationService)
        {
            _logger = logger;
            _reviewApplicationService = reviewApplicationService;
        }

        public async Task<IActionResult> Index()
        {
            var reviews = await _reviewApplicationService.GetAllActiveReviews();
            if (reviews == null)
            {
                ViewBag.ErrorMessage = "Cannot find any reviews.  Please check that the API is up and running.";
                return View();
            }
            return View(reviews.OrderBy(z => z.BookTitle).ToList());
        }
    }
}

BookReviews.MVCWebApplication/Views/Author/Add.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@using BookReviews.Models.Dto

@model AuthorDto

@using (Html.BeginForm("Add", "Author", FormMethod.Post))
{
    <table>
        <tr>
            <td>
                @Html.LabelFor(m => m.LastName, "Last Name:")
            </td>
            <td>
                @Html.TextBoxFor(m => m.LastName, new { @class= "form-control"})
            </td>
        </tr>

        <tr>
            <td>
                @Html.LabelFor(m => m.FirstName, "First Name:")
            </td>
            <td>
                @Html.TextBoxFor(m => m.FirstName, new { @class= "form-control"})
            </td>
        </tr>

        <tr>
            <td></td>
            <td>
                <input type="submit" value="Add" class="btn btn-primary" />
                @Html.ActionLink("Cancel","Index","Author",null, new { @class="btn btn-primary"})
            </td>
        </tr>
    </table>
}

BookReviews.MVCWebApplication/Views/Author/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@using BookReviews.Models.Dto

@model AuthorDto

@using (Html.BeginForm("Edit", "Author", FormMethod.Post))
{
    <table>
        <tr>
            <td>
                @Html.LabelFor(m => m.LastName, "Last Name:")
            </td>
            <td>
                @Html.TextBoxFor(m => m.LastName, new { @class= "form-control"})
            </td>
        </tr>

        <tr>
            <td>
                @Html.LabelFor(m => m.FirstName, "First Name:")
            </td>
            <td>
                @Html.TextBoxFor(m => m.FirstName, new { @class= "form-control"})
            </td>
        </tr>

        <tr>
            <td></td>
            <td>
                <input type="submit" value="Submit" class="btn btn-primary" />
                @Html.ActionLink("Cancel","Index","Author",null, new { @class="btn btn-primary"})
            </td>
        </tr>
    </table>
}

BookReviews.MVCWebApplication/Views/Author/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "../Shared/_Layout";
}

@using BookReviews.Models.Dto

@model List<AuthorDto>

@if (!string.IsNullOrEmpty(ViewBag.ErrorMessage))
{
    <div class="alert alert-danger" role="alert">
        @ViewBag.ErrorMessage
    </div>
}
else
{
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col"></th>
                <th scope="col"></th>
                <th scope="col">Last Name</th>
                <th scope="col">First Name</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var a in Model)
            {
                <tr>
                    <th scope="row">
                        @Html.ActionLink("Edit", "Edit", new { id=a.Id })
                    </th>
                    <th scope="row">
                        @Html.ActionLink("Delete", "Delete", new { id=a.Id })
                    </th>
                    <td>
                        @Html.Label(a.LastName)
                    </td>
                    <td>
                        @Html.Label(a.FirstName)
                    </td>
                </tr>
            }
        </tbody>
    </table>

    @Html.ActionLink("Add New","Add","Author",null, new { @class="btn btn-primary"})
}

BookReviews.MVCWebApplication/Views/Book/Add.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@using BookReviews.Models.Dto

@model BookDto

@using (Html.BeginForm("Add", "Book", FormMethod.Post))
{
    <table>
        <tr>
            <td>
                @Html.LabelFor(m => m.AuthorLastName, "Author Last Name:")
            </td>
            <td>
                @Html.TextBoxFor(m => m.AuthorLastName, new { @class= "form-control"})
            </td>
        </tr>

        <tr>
            <td>
                @Html.LabelFor(m => m.AuthorFirstName, "Author First Name:")
            </td>
            <td>
                @Html.TextBoxFor(m => m.AuthorFirstName, new { @class= "form-control"})
            </td>
        </tr>

        <tr>
            <td>
                @Html.LabelFor(m => m.Title, "Book Title:")
            </td>
            <td>
                @Html.TextBoxFor(m => m.Title, new { @class= "form-control"})
            </td>
        </tr>

        <tr>
            <td></td>
            <td>
                <input type="submit" value="Add" class="btn btn-primary" />
                @Html.ActionLink("Cancel","Index","Book",null, new { @class="btn btn-primary"})
            </td>
        </tr>
    </table>
}

BookReviews.MVCWebApplication/Views/Book/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@using BookReviews.Models.Dto

@model BookDto

@using (Html.BeginForm("Edit", "Book", FormMethod.Post))
{
    <table>
        <tr>
            <td>
                @Html.LabelFor(m => m.AuthorLastName, "Author Last Name:")
            </td>
            <td>
                @Html.TextBoxFor(m => m.AuthorLastName, new { @class= "form-control"})
            </td>
        </tr>

        <tr>
            <td>
                @Html.LabelFor(m => m.AuthorFirstName, "Author First Name:")
            </td>
            <td>
                @Html.TextBoxFor(m => m.AuthorFirstName, new { @class= "form-control"})
            </td>
        </tr>

        <tr>
            <td>
                @Html.LabelFor(m => m.Title, "Book Title:")
            </td>
            <td>
                @Html.TextBoxFor(m => m.Title, new { @class= "form-control"})
            </td>
        </tr>

        <tr>
            <td></td>
            <td>
                <input type="submit" value="Submit" class="btn btn-primary" />
                @Html.ActionLink("Cancel","Index","Book",null, new { @class="btn btn-primary"})
            </td>
        </tr>
    </table>
}

BookReviews.MVCWebApplication/Views/Book/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "../Shared/_Layout";
}

@using BookReviews.Models.Dto

@model List<BookDto>

@if (!string.IsNullOrEmpty(ViewBag.ErrorMessage))
{
    <div class="alert alert-danger" role="alert">
        @ViewBag.ErrorMessage
    </div>
}
else
{
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col"></th>
                <th scope="col"></th>
                <th scope="col">Title</th>
                <th scope="col">Author Last Name</th>
                <th scope="col">Author First Name</th>
                <th scope="col">Star Rating</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var a in Model)
            {
                <tr>
                    <th scope="row">
                        @Html.ActionLink("Edit", "Edit", new { id=a.Id })
                    </th>
                    <th scope="row">
                        @Html.ActionLink("Delete", "Delete", new { id=a.Id })
                    </th>
                    <td>
                        @Html.Label(a.Title)
                    </td>
                    <td>
                        @Html.Label(a.AuthorLastName)
                    </td>
                    <td>
                        @Html.Label(a.AuthorFirstName)
                    </td>
                    <td>
                        @{
                            switch (a.StarRating)
                            {
                                case 1:
                                    <text>
                                        <h3>*</h3>
                                    </text>
                                    break;
                                case 2:
                                    <text>
                                        <h3>**</h3>
                                    </text>
                                    break;
                                case 3:
                                    <text>
                                        <h3>***</h3>
                                    </text>
                                    break;
                                case 4:
                                    <text>
                                        <h3>****</h3>
                                    </text>
                                    break;
                                case 5:
                                    <text>
                                        <h3>*****</h3>
                                    </text>
                                    break;
                                default:
                                    <text>
                                        No Ratings Yet
                                    </text>
                                    break;
                            }
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>

    @Html.ActionLink("Add New","Add","Book",null, new { @class="btn btn-primary"})
}

BookReviews.MVCWebApplication/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    Layout = "../Shared/_Layout";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>

    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col"></th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th scope="row">
                    @Html.ActionLink("Authors", "Index", "Author")
                </th>
                <td>
                    <h3>
                        Add, Edit or Delete from the list of Authors
                    </h3>
                </td>
            </tr>
            <tr>
                <th scope="row">
                    @Html.ActionLink("Books", "Index", "Book")
                </th>
                <td>
                    <h3>
                        Add, Edit or Delete from the list of Books
                    </h3>
                </td>
            </tr>
            <tr>
                <th scope="row">
                    @Html.ActionLink("Reviews", "Index", "Review")
                </th>
                <td>
                    <h3>
                        Create book reviews to keep track of what you've read
                    </h3>
                </td>
            </tr>
    </table>
</div>

BookReviews.MVCWebApplication/Views/Home/Login.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@using BookReviews.Models.Dto

@model UserDto

@using (Html.BeginForm("Login", "Home", FormMethod.Post))
{
    @Html.LabelFor(m => m.Email, "Email:")
    @Html.TextBoxFor(m => m.Email)

    @Html.LabelFor(m => m.Password, "Password:")
    @Html.TextBoxFor(m => m.Password)

    <input type="submit" value="Submit" />
}

BookReviews.MVCWebApplication/Views/Review/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@using BookReviews.Models.Dto

@model List<ReviewDto>

@if (!string.IsNullOrEmpty(ViewBag.ErrorMessage))
{
    <div class="alert alert-danger" role="alert">
        @ViewBag.ErrorMessage
    </div>
}
else
{
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col"></th>
                <th scope="col"></th>
                <th scope="col">Title</th>
                <th scope="col">Author Name</th>
                <th scope="col">User Name</th>
                <th scope="col">Star Rating</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var a in Model)
            {
                <tr>
                    <th scope="row">
                        @Html.ActionLink("Edit", "Edit", new { id=a.Id })
                    </th>
                    <th scope="row">
                        @Html.ActionLink("Delete", "Delete", new { id=a.Id })
                    </th>
                    <th>
                        @Html.Label(a.BookTitle)
                    </th>
                    <td>
                        @Html.Label(a.AuthorLastName), @Html.Label(a.AuthorFirstName)
                    </td>
                    <td>
                        @Html.Label(a.UserLastName), @Html.Label(a.UserFirstName)
                    </td>
                    <th>
                        @Html.Label(a.StarRatingText)
                    </th>
                    <th>
                        @Html.Label(a.StarRatingValue)
                    </th>
                </tr>
            }
        </tbody>
    </table>

    @Html.ActionLink("Add New","Add","Author",null, new { @class="btn btn-primary"})
}

BookReviews.MVCWebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookReviews.MVCWebApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BookReviews.MVCWebApplication.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BookReviews.MVCWebApplication</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Author" asp-action="Index">Authors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index">Books</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Review" asp-action="Index">Reviews</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - BookReviews.MVCWebApplication - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>